DROP TABLE IF EXISTS calc;

CREATE TABLE calc(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  salary INTEGER NOT NULL,
  total_hours INTEGER NOT NULL,
  purchase_amount INTEGER NOT NULL,
  hours_calc INTEGER NOT NULL
);